app: getUserSig
stage: prod

component: scf
name: getUserSig

inputs:
  name: ${name}-${stage}-${app}
  namespace: default
  description: For https://cloud.tencent.com/document/product/647/17275
  handler: index.main_handler
  runtime: Nodejs12.16
  region: ap-guangzhou
  timeout: 30
  src: ./
  environment:
    variables:
      TRTC_SDK_APPID: ${env:TRTC_SDK_APPID}
      TRTC_SECRET_KEY: ${env:TRTC_SECRET_KEY}
  events:
    - apigw:
        parameters:
          environment: release
          endpoints:
            - path: /
              method: ANY # GET POST PUT DELETE HEAD ANY
              enableCORS: true
              responseType: JSON
          protocols:
            - http
            - https

# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

