app: apaas
stage: prod

component: http
name: trtc-usersig

inputs:
  src: ./
  region: ap-guangzhou
  faas:
    runtime: Nodejs12.16
    framework: koa
    name: ${name}-${stage}-${app}
    timeout: 10
    environments:
      - key: TRTC_TIM_APPID
        value: ${env:TRTC_TIM_APPID}
      - key: TRTC_TIM_SECRET
        value: ${env:TRTC_TIM_SECRET}
  apigw:
    isDisabled: false
    environment: release
    api:
      path: /
      cors: true
      timeout: 30
      qualifier: $DEFAULT
    protocols:
      - http
      - https

# https://github.com/serverless-components/tencent-http/blob/master/docs/configure.md

